import { type NextPage } from "next";
import Head from "next/head";

import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import MainLayout from "../components/MainLayout";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>My website</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className="h-screen bg-[url('/rose-petals.svg')] bg-cover object-fill">
        <Navbar />
        <MainLayout />
        <a className="text-gray-200" href="/blogg">
          a href blogg
        </a>
        <Link className="text-gray-200" href="/blogg">
          {" "}
          Link til blogg
        </Link>
        <Footer />
      </body>
    </>
  );
};

export default Home;
